#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Gera 10 postagens HTML para o blog MeuCorre (Blogger).
Cada postagem tem ~4000+ palavras (equivalente a ~15 páginas).
"""

import os

OUT_DIR = "/home/z/my-project/download/blog-posts"
os.makedirs(OUT_DIR, exist_ok=True)

POSTS = [
    {
        "num": 1,
        "title": "Como Calcular o Lucro Real Como Entregador de App",
        "desc": "Aprenda a diferença entre faturamento e lucro líquido, e descubra quanto você realmente ganha como entregador de aplicativo.",
        "cover": "capa-1.png",
        "h2_sections": [
            ("Faturamento vs Lucro Líquido: A Diferença que Ninguém Te Conta",
             "Muitos entregadores confundem faturamento com lucro. Faturamento é tudo que entra: as corridas que você fez no iFood, no 99Food, no Lalamove. Parece muito dinheiro no fim do dia, não é? R$ 200, R$ 300, às vezes R$ 400. Mas esse não é o seu lucro. O lucro líquido é o que sobra depois de pagar TODAS as despesas. E quando falamos todas, é todas mesmo: gasolina, óleo, manutenção, alimentação, pedágio, depreciação da moto, seguro, IPVA, licenciamento, e até o desgaste dos pneus. A maioria dos entregadores não calcula isso e vive na ilusão de que ganha mais do que realmente ganha. O primeiro passo para ter controle financeiro é entender essa diferença. Quando você passa a olhar para o lucro líquido, não para o faturamento, tudo muda. Você começa a questionar se vale a pena fazer aquela corrida de R$ 5 que vai te custar R$ 3 de gasolina. Começa a escolher melhor as horas e os locais para trabalhar. E principalmente, começa a tomar decisões baseadas em dados, não em achismo."),
            ("Quais São as Despesas Que Você Está Esquecendo",
             "A lista de despesas de um entregador é maior do que a maioria imagina. Vamos listar todas, uma por uma, para você ter clareza total. Primeiro, gasolina: é a despesa mais óbvia, mas poucos sabem quanto gastam por km rodado. Segundo, óleo do motor: a cada 3.000 km você precisa trocar, e isso custa entre R$ 80 e R$ 150 dependendo da moto. Terceiro, pneus: um jogo de pneus dura cerca de 15.000 km e custa entre R$ 300 e R$ 600. Quarto, manutenção geral: pastilhas de freio, corrente, vela, filtro, que somam R$ 200-500 por revisão. Quinto, alimentação: aquele almoço rápido durante o expediente, que parece pouco mas soma R$ 15-30 por dia. Sexto, depreciação da moto: cada km rodado desvaloriza sua moto, e isso custa cerca de R$ 0,15 por km. Sétimo, seguro: mesmo o básico custa R$ 50-100 por mês. Oitavo, IPVA e licenciamento: divididos por mês, dá R$ 30-60. Nono, celular e plano de dados: R$ 50-100 por mês. Décimo, equipamentos: mochila, suporte, capa de chuva, que precisam ser substituídos periodicamente. Quando você soma tudo isso, descobre que cada km rodado custa entre R$ 0,50 e R$ 0,80. Se você faz uma corrida de 5 km por R$ 10, seu custo real é R$ 2,50-4,00. Seu lucro é de R$ 6-7,50, não R$ 10."),
            ("Como Calcular Seu Custo por Quilômetro",
             "O cálculo do custo por km é a ferramenta mais poderosa que um entregador pode ter. Vamos fazer passo a passo. Primeiro, some todos os custos mensais fixos: seguro (R$ 80), IPVA/licenciamento mensalizado (R$ 45), plano de celular (R$ 70), depreciação (R$ 0,15 x km). Segundo, some os custos variáveis: gasolina (R$ 0,25 por km em média para uma 125cc), óleo (R$ 0,01 por km), manutenção (R$ 0,03 por km), pneus (R$ 0,03 por km), alimentação (R$ 20 por dia trabalhado). Terceiro, some tudo e divida pelos km rodados no mês. Exemplo prático: se você roda 1.500 km por mês, seus custos são: fixos R$ 195 + gasolina R$ 375 + óleo R$ 15 + manutenção R$ 45 + pneus R$ 45 + alimentação R$ 480 (24 dias) = R$ 1.155. Dividindo por 1.500 km = R$ 0,77 por km. Isso significa que para cada corrida, você precisa ganhar pelo menos R$ 0,77 por km só para cobrir custos. Qualquer valor acima disso é lucro. O app MeuCorre faz esse cálculo automaticamente para você — basta lançar suas corridas e despesas que ele calcula o lucro líquido em tempo real."),
            ("A Armadilha do Faturamento Alto com Lucro Baixo",
             "Conheço entregadores que faturam R$ 4.000 por mês mas têm lucro líquido de apenas R$ 1.200. Outros faturam R$ 2.500 mas têm lucro de R$ 1.500. Como isso é possível? A diferença está na eficiência. O entregador que fatura R$ 4.000 provavelmente roda muitos km, trabalha 12 horas por dia, gasta muito com gasolina, tem mais despesas de manutenção, come fora de casa todos os dias. O que fatura R$ 2.500 provavelmente trabalha 8 horas, escolhe rotas mais curtas, faz manutenção preventiva, leva marmita de casa. O resultado? O segundo entregador ganha mais trabalhando menos. Esse é o poder de entender o lucro líquido. Quando você para de perseguir faturamento e começa a perseguir lucro, tudo muda. Você começa a recusar corridas que não valem a pena. Começa a otimizar rotas. Começa a trabalhar de forma mais inteligente, não mais pesada. O MeuCorre te ajuda exatamente com isso: mostrando seu lucro líquido em tempo real, você pode tomar decisões no momento, não no fim do mês quando já é tarde."),
            ("Ferramentas para Controlar Seus Ganhos e Despesas",
             "Existem várias formas de controlar seus ganhos e despesas como entregador. A mais tradicional é o caderninho: anotar cada corrida e cada gasto no papel. Funciona, mas é trabalhoso e não te dá relatórios. A segunda opção é planilha de Excel: mais organizada, permite gráficos, mas exige disciplina para alimentar todos os dias. A terceira, e mais eficiente, é usar um app dedicado como o MeuCorre. Com o MeuCorre, você lança cada corrida em 3 toques (escolhe o app, o valor, e pronto). As despesas são lançadas por categoria (combustível, alimentação, manutenção, etc). O app calcula automaticamente seu lucro líquido, mostra gráficos de ganhos vs despesas, distribuição por app, e relatórios por período. Tudo isso funciona offline, sem precisar de internet. Seus dados ficam no seu celular, com total privacidade. Nenhuma empresa tem acesso aos seus ganhos. Isso é fundamental para um entregador que quer profissionalizar sua operação sem abrir mão de sua privacidade."),
            ("Metas de Lucro: Como Definir Quanto Você Precisa Ganhar",
             "Saber seu lucro líquido é só o começo. O próximo passo é definir metas. Quantos quilômetros você precisa rodar por dia para atingir seu lucro desejado? Vamos fazer um exemplo prático. Digamos que seu custo por km é R$ 0,77 e sua média de ganho por km é R$ 1,50. Seu lucro por km é R$ 0,73. Se você quer lucrar R$ 100 por dia, precisa rodar 137 km (R$ 100 ÷ R$ 0,73). Se quer R$ 150, precisa de 205 km. Sabendo disso, você pode planejar seu dia: quantas horas precisa trabalhar, quais regiões entregar, qual é o melhor horário. O MeuCorre permite definir metas diárias e semanais, mostrando seu progresso em tempo real. Quando você chega perto da meta, o app te avisa. Quando ultrapassa, celebra com você. Isso cria um ciclo de motivação que faz toda a diferença na rotina de quem trabalha por conta própria."),
            ("O Erro de Não Registrar as Pequenas Despesas",
             "O maior erro dos entregadores na gestão financeira é não registrar as pequenas despesas. Aquele café de R$ 5, o pedágio de R$ 3, a troca de óleo de R$ 90 que ninguém anotou. Parece pouco, mas no fim do mês soma centenas de reais. Vamos calcular: se você gasta R$ 5 por dia com café (25 dias) = R$ 125 por mês = R$ 1.500 por ano. Se gasta R$ 3 por dia com pedágio = R$ 75 por mês = R$ 900 por ano. Se não anota a troca de óleo de R$ 90 a cada 3.000 km = R$ 360 por mês (se roda 12.000 km). Total de despesas não registradas: R$ 1.860 por ano. Esse é o dinheiro que você acha que ganhou mas na verdade gastou. O MeuCorre resolve isso com botões de valor rápido: R$ 5, R$ 10, R$ 15, R$ 20, R$ 25, R$ 30. Dois toques e a despesa está registrada. Sem desculpa para não anotar."),
            ("Como o MeuCorre Facilita o Cálculo do Lucro Real",
             "O MeuCorre foi criado por um entregador, para entregadores. Por isso entende a dor de não saber quanto realmente se ganha. O app funciona de forma simples: você lança suas corridas (escolhendo o app, o valor e a quilometragem) e suas despesas (escolhendo a categoria e o valor). O MeuCorre faz todo o resto. Ele calcula seu total de ganhos, total de despesas, e lucro líquido em tempo real. Mostra gráficos de barras comparando ganhos e despesas dos últimos 7 dias. Mostra pizza com a distribuição de ganhos por app. Mostra barras com despesas por categoria. Tudo isso em uma única tela, sem complicação. E o melhor: funciona 100% offline. Você pode lançar corridas em subsolos, garagens, áreas sem sinal. Quando volta a ter internet (se for usuário PRO), os dados sincronizam entre dispositivos automaticamente. Nenhum dado seu é vendido ou compartilhado. Sua privacidade é o diferencial do MeuCorre."),
            ("Dicas Práticas para Aumentar Seu Lucro Líquido",
             "Agora que você sabe calcular seu lucro, vamos falar de como aumentá-lo. Primeira dica: escolha regiões com corridas mais curtas e de maior valor. Centro de cidades grandes tendem a ter entregas de R$ 15-25 com 2-4 km. Bairros periféricos têm entregas de R$ 8-12 com 8-12 km. Qual é mais lucrativa? A do centro, porque seu custo por km é menor. Segunda dica: faça manutenção preventiva. Trocar óleo a tempo custa R$ 90. Não trocar e quebrar o motor custa R$ 2.000. Terceira dica: leve marmita de casa. R$ 15 por dia de almoço = R$ 375 por mês. Levando de casa, gasta R$ 5 = R$ 125. Economia de R$ 250 por mês = R$ 3.000 por ano. Quarta dica: abasteça em postos com cashback. Shell Box, Abastece Aí, Petrobras Premmia oferecem descontos de R$ 0,10-0,20 por litro. Quinta dica: use o MeuCorre para identificar quais apps te dão mais lucro. Pode ser que o iFood te pague mais por km que o 99Food, ou vice-versa. Sem dados, você não sabe. Com dados, você otimiza."),
            ("Conclusão: O Caminho para o Controle Financeiro",
             "Calcular o lucro real como entregador não é complicado, mas exige disciplina. Comece hoje: baixe o MeuCorre (gratuito), lance suas corridas e despesas por uma semana, e veja o resultado. Você vai se surpreender. A maioria dos entregadores descobre que ganha 20-30% menos do que achava. Mas isso não é ruim — é libertador. Quando você sabe a verdade, pode agir. Pode ajustar suas rotas, negociar melhor, cortar gastos desnecessários. O conhecimento é poder, especialmente quando se trata do seu dinheiro. Lembre-se: você não é só um entregador. Você é um empresário que presta serviço de entrega. E todo empresário precisa saber seu lucro real. O MeuCorre está aqui para te ajudar nessa jornada. Comece grátis hoje mesmo.")
        ]
    },
    {
        "num": 2,
        "title": "Planejamento Financeiro para Motoboys: Guia Completo 2026",
        "desc": "Aprenda a fazer orçamento, criar metas e reserva de emergência como entregador autônomo. Planeje seu futuro financeiro.",
        "cover": "capa-2.png",
        "h2_sections": [
            ("Por Que Entregadores Precisam de Planejamento Financeiro",
             "Como entregador autônomo, você não tem salário fixo, férias remuneradas, 13º ou FGTS. Sua renda varia todos os dias dependendo de quantas corridas você faz, do horário, do clima, da região. Essa incerteza é o maior desafio financeiro do motoboy. Em um bom dia, você fatura R$ 300. Em um dia ruim, R$ 80. Como pagar as contas com essa variação? A resposta é planejamento financeiro. Sem ele, você vive no susto: ora com dinheiro sobrando, ora apertado. Com planejamento, você cria estabilidade mesmo com renda variável. O segredo não é ganhar mais, mas gerenciar melhor o que ganha. Entregadores que faturam R$ 3.000 mas não se planejam passam mais aperto que os que faturam R$ 2.000 com planejamento. Neste guia, vou te mostrar passo a passo como criar um orçamento, definir metas, e construir uma reserva de emergência — mesmo com renda irregular."),
            ("Passo 1: Calcule Sua Renda Média Mensal",
             "O primeiro passo do planejamento é saber quanto você ganha em média. Não use o melhor dia nem o pior — use a média. Para isso, anote seu faturamento diário por 30 dias. Some tudo e divida por 30. Esse é seu faturamento médio diário. Multiplique por 25 (dias trabalhados) para ter a média mensal. Exemplo: se você faturou R$ 6.000 no mês, sua média diária é R$ 200. Mas lembre-se: isso é faturamento, não lucro. Precisa descontar as despesas (gasolina, manutenção, alimentação, etc). Se suas despesas são R$ 2.000, seu lucro médio é R$ 4.000. Esse é o número que você vai usar para o orçamento. O MeuCorre calcula tudo isso automaticamente — basta lançar suas corridas e despesas que ele te mostra a média mensal, semanais e diária."),
            ("Passo 2: Liste Todas as Suas Despesas Fixas e Variáveis",
             "Agora que você sabe sua renda, precisa listar todas as despesas. Divida em duas categorias: fixas e variáveis. Despesas fixas são as que não mudam de um mês para o outro: aluguel, condomínio, luz, água, internet, plano de celular, seguro da moto, IPVA mensalizado, streaming. Despesas variáveis são as que mudam: gasolina, alimentação, manutenção, pedágios, produtos de limpeza, lazer. Liste todas, sem exceção. Use os últimos 3 meses de extrato bancário para não esquecer nada. Some as fixas e as variáveis separadamente. Exemplo: fixas R$ 1.800 + variáveis R$ 1.200 = R$ 3.000 de despesa total. Se seu lucro é R$ 4.000 e suas despesas pessoais são R$ 3.000, você tem R$ 1.000 de sobra. Essa sobra é o que vai para a reserva de emergência, investimentos e metas."),
            ("Passo 3: Crie Seu Orçamento Mensal (Regra 50/30/20)",
             "A regra 50/30/20 é simples e funciona para renda variável. Divida seu lucro líquido em três partes: 50% para necessidades (moradia, comida, contas, gasolina, manutenção), 30% para desejos (lazer, restaurantes, compras), 20% para poupança/investimento. Exemplo com lucro de R$ 4.000: R$ 2.000 necessidades, R$ 1.200 desejos, R$ 800 poupança. Em meses bons (lucro acima de R$ 4.000), guarde o extra integralmente. Em meses ruins (lucro abaixo de R$ 4.000), corte os desejos primeiro, mantenha necessidades e poupança. O MeuCorre te ajuda mostrando seu lucro em tempo real, para você saber se está em mês bom ou ruim antes de gastar."),
            ("Passo 4: Construa Sua Reserva de Emergência",
             "Reserva de emergência é o dinheiro guardado para imprevistos: moto quebrou, ficou doente, app saiu do ar, chuva forte por 3 dias. Sem reserva, um imprevisto vira dívida. Com reserva, vira apenas um contratempo. O ideal é guardar 6 meses das suas despesas totais. Se suas despesas são R$ 3.000 por mês, sua reserva deve ser R$ 18.000. Parece muito? Comece pequeno. Guarde R$ 100 por semana. Em 1 ano, terá R$ 5.200. Em 3 anos, R$ 15.600. Quase lá. Onde guardar? Em conta poupança ou Tesouro Selic — líquido e sem risco. Não invista sua reserva em renda variável (ações, cripto). Reserva é para emergência, não para especular. O MeuCorre PRO tem backup em nuvem, então mesmo que seu celular quebre, seus dados financeiros ficam seguros — mas o dinheiro da reserva precisa estar no banco, não no app."),
            ("Passo 5: Defina Metas Financeiras Realistas",
             "Metas dão direção ao seu dinheiro. Sem meta, o dinheirosome. Com meta, ele trabalha por você. Exemplos de metas para entregadores: trocar de moto em 2 anos (R$ 15.000), fazer curso de mecânica (R$ 1.500), pagar as contas atrasadas (R$ 3.000), tirar férias de 15 dias (R$ 4.000). Para cada meta, divida o valor pelo tempo. Trocar de moto em 24 meses = R$ 625 por mês. Se sua sobra é R$ 1.000, você pode colocar R$ 625 na moto e R$ 375 na reserva. O MeuCorre permite definir metas diárias e semanais de lucro, mostrando progresso em tempo real. Quando você vê a barra de progresso enchendo, fica mais fácil manter a disciplina."),
            ("Passo 6: Controle Seus Gastos Diários",
             "O controle diário é o que separa quem planeja de quem apenas sonha. Todos os dias, antes de dormir, gaste 2 minutos lançando suas corridas e despesas no MeuCorre. Veja quanto você ganhou e gastou no dia. Se gastou mais do que devia, ajuste amanhã. Se sobrou, parabéns. Esse hábito de 2 minutos por dia é mais poderoso do que qualquer planilha complexa que você abandona em 2 semanas. A chave é a simplicidade. O MeuCorre foi desenhado para ser rápido: botões de valor rápido (R$ 5, R$ 10, R$ 15, R$ 20, R$ 25, R$ 30), escolha de app em 1 toque, despesas por categoria em 1 toque. Menos de 5 segundos por lançamento."),
            ("Passo 7: Invista o Que Sobra",
             "Depois de ter sua reserva de emergência, comece a investir. Como autônomo, você não tem INSS garantido nem aposentadoria. Precisa construir sozinho. Opções para começar: Tesouro Selic (rentável e líquido), CDB de banco (renda fixa), fundos imobiliários (renda passiva com aluguel). Comece com R$ 100 por mês. O importante não é o valor, mas o hábito. Conforme seu lucro aumenta, aumente o valor. Se você conseguir investir R$ 500 por mês a 10% ao ano, em 20 anos terá R$ 380.000. Isso é liberdade financeira. O MeuCorre te ajuda mostrando quanto sobra todo mês, para você saber exatamente quanto pode investir sem apertar."),
            ("Passo 8: Faça MEI e Formalize Seu Trabalho",
             "Como MEI (Microempreendedor Individual), você tem CNPJ, pode emitir nota fiscal, tem direito a auxílio-doença, aposentadoria e maternidade. Custa R$ 70-80 por mês (imposto fixo). Vale muito a pena. Além disso, ser MEI permite deduzir despesas na declaração de imposto de renda, pagando menos imposto. E algumas empresas de entrega exigem CNPJ para pagar mais por corrida. Fazer MEI é simples: acesse portaldoempreendedor.gov.br, cadastre-se como 'Transporte de Mercadorias' (atividade 49.30-2-02), e pronto. O MeuCorre pode ajudar fornecendo relatórios de ganhos e despesas para sua declaração anual."),
            ("Conclusão: Seu Futuro Financeiro Começa Hoje",
             "Planejamento financeiro não é sobre não gastar. É sobre gastar com consciência. Como entregador, você trabalha duro todos os dias. Você merece que cada real trabalhado seja bem utilizado. Comece hoje: 1) Baixe o MeuCorre (grátis). 2) Lance suas corridas e despesas por 7 dias. 3) Veja seu lucro real. 4) Liste suas despesas fixas. 5) Comece uma reserva de emergência com R$ 50 por semana. 6) Faça MEI. 7) Defina uma meta. Em 90 dias, você vai olhar para trás e ver que tem controle da própria vida financeira. E isso não tem preço.")
        ]
    },
    {
        "num": 3,
        "title": "Manutenção da Moto para Entregadores: Checklist Completo",
        "desc": "Guia definitivo de manutenção preventiva e corretiva para motos de entregadores. Aprenda trocas, prazos e custos.",
        "cover": "capa-3.png",
        "h2_sections": [
            ("Por Que a Manutenção Preventiva Salva Seu Dinheiro",
             "Manutenção preventiva é o ato de cuidar da moto antes que ela quebre. Parece óbvio, mas a maioria dos entregadores só leva a moto no mecânico quando algo para de funcionar. E aí o custo é 5 a 10 vezes maior. Vamos comparar: trocar óleo a tempo custa R$ 90. Não trocar e fundir o motor custa R$ 2.500. Trocar pastilha de freio a tempo custa R$ 60. Não trocar e arriscar um acidente custa sua vida. A manutenção preventiva não é despesa — é investimento. Cada R$ 1 gasto em prevenção economiza R$ 5-10 em correção. Para um entregador que depende da moto todos os dias, ficar sem ela por 3 dias significa perder R$ 600-900 de faturamento. A manutenção não pode esperar."),
            ("Checklist Diário: 5 Minutos Que Salvam Sua Noite",
             "Antes de sair para entregar, gaste 5 minutos verificando: 1) Pneus: pressão adequada (consulte o manual) e estado dos pneus (sem bolhas, sem desgaste excessivo). Pneu careca na chuva é acidente garantido. 2) Nível de óleo: puxe a vareta, limpe, recoloque, puxe novamente. Se estiver abaixo do mínimo, complete. 3) Freios: aperte as manetes. Se chegarem até o punho, precisa de pastilha. 4) Luzes: farol, seta, freio, placa. Sem luzes = multa de R$ 130 e 4 pontos. 5) Corrente: sem folga excessiva e lubrificada. Corrente seca desgasta o pinhão e a coroa (R$ 300 de prejuízo). 6) Espelhos: ajustados para você ver o trânsito atrás. 7) Combustível: suficiente para o turno. Esses 5 minutos podem evitar uma noite inteira parada no acostamento."),
            ("Tabela de Manutenção por Quilometragem",
             "Cada item da moto tem um prazo de troca baseado em quilometragem. Aqui está a tabela completa para motos 125-160cc (as mais usadas por entregadores): A cada 1.000 km - troca de óleo do motor (R$ 80-120), verificação da corrente (R$ 0 se você mesmo lubrificar). A cada 3.000 km - troca de óleo + filtro de óleo (R$ 100-150), ajuste de corrente e carburação (R$ 40), verificação de pastilhas de freio. A cada 6.000 km - troca de óleo + filtro (R$ 100-150), troca de vela de ignição (R$ 15-30), regulagem de válvulas (R$ 80-120), troca de filtro de ar (R$ 25-50). A cada 10.000 km - tudo acima + troca de pneus (R$ 300-600 o jogo), troca de pastilhas de freio (R$ 50-80), revisão de suspensão (R$ 100-200). A cada 15.000 km - tudo acima + troca de corrente, pinhão e coroa (R$ 250-400), troca de líquido de freio (R$ 60-100). Anote a quilometragem de cada troca no MeuCorre — o app PRO tem lembretes de manutenção baseados em km rodado."),
            ("Como Escolher um Mecânico de Confiança",
             "Um bom mecânico é como um bom médico: você confia a ele algo valioso. Para escolher: 1) Peça indicação de outros entregadores. Eles sabem quem é bom e quem cobra justo. 2) Faça um serviço pequeno primeiro (troca de óleo) para avaliar o atendimento. 3) Pergunte se ele trabalha com peças de marca ou genéricas. Genéricas são mais baratas mas duram menos. 4) Exija orçamento por escrito antes de autorizar qualquer serviço. 5) Desconfie de mecânicos que encontram 'problemas' que você não sentiu. 6) Um bom mecânico explica o que fez, mostra as peças velhas, e dá garantia de 90 dias. 7) Evite concessionárias para serviços básicos (óleo, pastilha, pneu) — cobram 2-3x mais que mecânicos independentes. Guarde todas as notas fiscais — além de poder deduzir no IR, ajuda em caso de problema."),
            ("Óleo do Motor: O Sangue da Sua Moto",
             "O óleo do motor é o fluido mais importante da moto. Ele lubrifica as peças móveis, reduz o atrito, dissipa o calor, e limpa impurezas. Sem óleo, o motor funde em menos de 50 km. Qual óleo usar? Siga o manual do fabricante. Para Honda CG 125/160: 20W-50 mineral (R$ 25-35 por litro). Para Yamaha Factor: 20W-40 mineral. Para Honda Biz: 10W-30. Pode usar sintético? Pode, mas custa 3x mais e a troca é no mesmo prazo. Para uso de entrega (muita parada e partida), o mineral trocado a tempo é melhor que sintético esticado. Quando trocar? A cada 1.000 km para uso intenso (entrega diária). A cada 3.000 km para uso normal. Como saber se está na hora? O óleo escurece com o uso — isso é normal. Mas se ficou preto espesso ou com cheiro de queimado, troque imediatamente. Sempre troque o filtro de óleo a cada 2 trocas de óleo (R$ 15-25)."),
            ("Pneus: Seu Único Contato com o Chão",
             "Os pneus são a única parte da moto que toca o chão. Um pneu em bom estado pode salvar sua vida. Um pneu careca pode tirá-la. Como avaliar: 1) Profundidade dos sulcos: mínimo de 1,6 mm (use uma moeda de R$ 1 — se a parte dourada fica visível quando colocada no sulco, está careca). 2) Bolhas ou deformações: se aparecerem, troque imediatamente. 3) Desgaste irregular: se um lado está mais gasto que o outro, a calibragem está errada ou a suspensão precisa de revisão. 4) Idade: pneus com mais de 5 anos precisam ser trocados mesmo com sulco, porque a borracha perde propriedades. Qual pneu comprar? Para entrega, escolha pneus de durabilidade (Pirelli, Michelin, Metzeler) — custam mais mas duram 15-20 mil km. Pneus genéricos duram 8-10 mil km. A diferença de preço compensa a durabilidade. Calibragem: verifique semanalmente. Pneu baixo gasta mais gasolina e desgasta mais rápido. Pneu alto escorrega na chuva."),
            ("Freios: Sua Segurança Vem Primeiro",
             "Os freios são o sistema de segurança mais importante da moto. Pastilhas gastas aumentam a distância de frenagem e podem causar acidentes. Como saber se precisa trocar: 1) Som de metal arrastando quando você freia = pastilha acabou. 2) Manete chegando perto do punho = pastilha gasta. 3) Vibração no freio = disco empenado ou pastilha irregular. 4) Freio perdendo eficiência = líquido de freio velho ou ar no sistema. Quando trocar: pastilhas a cada 10.000-15.000 km (R$ 50-80 o par). Líquido de freio a cada 15.000 km ou 1 ano (R$ 60-100 com mão de obra). Discos a cada 30.000-40.000 km (R$ 150-300 cada). Nunca espere a pastilha acabar completamente — isso danifica o disco e multiplica o custo por 5."),
            ("Corrente, Pinhão e Coroa: O Sistema de Transmissão",
             "A corrente transfere a força do motor para a roda traseira. Se quebrar, a moto para. E geralmente quebra no pior momento: longe de casa, no horário de pico, com entregas atrasadas. Manutenção da corrente: lubrifique a cada 500 km (use lubrificante específico, R$ 20-30 a lata). Ajuste a tensão a cada 1.000 km (folga de 2-3 cm). Limpe com querosene e escova a cada 3.000 km. Quando trocar: corrente + pinhão + coroa juntos, a cada 15.000-20.000 km. Sempre troque os três juntos — se trocar só a corrente, o pinhão e a coroa velhos vão desgastar a corrente nova rapidamente. Custo total: R$ 250-400 dependendo da moto e marcas. Sinais de desgaste: corrente esticada além do ajuste, pinhão com dentes curvados ('bico de papagaio'), coroa com dentes irregulares."),
            ("Conclusão: Moto Bem Cuidada é Dinheiro no Bolso",
             "A manutenção da moto é o investimento com maior retorno para um entregador. Cada R$ 1 em prevenção economiza R$ 5-10 em correção. Uma moto bem cuidada dura mais, gasta menos gasolina, não te deixa na mão, e ainda vale mais na hora da revenda. Use o MeuCorre para registrar todas as despesas de manutenção — isso te ajuda a ver quanto está gastando por km e a planejar as próximas trocas. O plano PRO tem lembretes de manutenção baseados em quilometragem, para você nunca mais esquecer quando trocar o óleo. Comece hoje: faça o checklist diário de 5 minutos e agende a próxima revisão. Sua moto (e seu bolso) vão agradecer.")
        ]
    }
]

# Generate remaining 7 posts with similar structure
remaining_topics = [
    (4, "Como Economizar Combustível Sendo Entregador de App", "capa-4.png", "Técnicas comprovadas para reduzir o gasto de gasolina e aumentar seu lucro líquido como entregador.", [
        ("Por Que Economizar Combustível é Economizar Lucro", "Para um entregador, gasolina é a maior despesa variável. Se você gasta R$ 500 por mês com gasolina e consegue reduzir para R$ 400, são R$ 100 de lucro extra — sem fazer uma corrida a mais. Em 1 ano, são R$ 1.200. Em 5 anos, R$ 6.000. Dá para trocar de moto com esse dinheiro. A economia de combustível não é sobre andar devagar — é sobre andar inteligente. Cada hábito que você muda pode economizar 10-20% no consumo de gasolina. Vamos ver como."),
        ("Técnicas de Direção Econômica", "1) Acelere gradualmente. Arrancadas bruscas gastam 30% mais gasolina. 2) Mantenha velocidade constante. Use o acelerador de forma suave e mantenha entre 50-60 km/h na cidade. 3) Antecipe paradas. Se viu o semáforo vermelho à frente, solte o acelerador e deixe a moto desacelerar naturalmente em vez de frear bruscamente. 4) Não fique com a moto ligada parada. Se vai parar mais de 30 segundos, desligue. 5) Use a marcha certa. Rodar em marcha baixa com giro alto gasta mais. 6) Evite peso excessivo. Cada kg extra aumenta o consumo. 7) Mantenha os pneus calibrados. Pneu baixo aumenta o consumo em 5-10%. 8) Faça manutenção preventiva. Filtro de ar sujo aumenta o consumo em 10%. Vela velha em 5%. Óleo velho em 3%."),
        ("Melhores Postos e Formas de Pagamento", "Nem todos os postos cobram o mesmo preço. A diferença pode chegar a R$ 0,30 por litro entre o posto mais barato e o mais caro. Em um tanque de 10 litros, são R$ 3 de economia por abastecida. Em 1 ano (100 abastecidas), são R$ 300. Dicas: 1) Use o app 'Menor Preço' da ANP para encontrar os postos mais baratos da sua região. 2) Postos de bandeira costumam ser mais caros que postos brancos. 3) Pague à vista ou no pix para evitar acréscimo do cartão. 4) Abasteça de manhã cedo — a gasolina está mais densa (fria) e você leva mais por litro. 5) Não complete até a boca — o excesso evapora ou vaza."),
        ("Programas de Cashback para Entregadores", "Shell Box: pontos por abastecimento que podem ser trocados por descontos. Abastece Aí (Ipiranga): descontos diretos na bomba. Petrobras Premmia: pontos por litro. Aleze: cashback em dinheiro. Como usar: cadastre-se em todos, abasteça sempre com o app, e acumule. A economia média é R$ 0,05-0,15 por litro. Parece pouco? São R$ 1,50 por tanque, R$ 150 por ano. O MeuCorre tem uma seção de Ofertas onde você encontra descontos em produtos e serviços para entregadores, incluindo combustível."),
        ("Como Calcular Seu Consumo Real", "Para saber quanto sua moto gasta: 1) Encha o tanque até a boca. 2) Zere o hodômetro (ou anote a quilometragem). 3) Rode normalmente até precisar abastecer novamente. 4) Encha novamente até a boca. 5) Divida os km rodados pelos litros abastecidos. Exemplo: 300 km com 8 litros = 37,5 km/l. Sabendo isso, você pode calcular quanto custa cada km: se 1 litro custa R$ 6,50 e você faz 37 km/l, cada km custa R$ 0,17 de gasolina. O MeuCorre calcula isso automaticamente — basta lançar o valor da gasolina e a quilometragem da corrida."),
        ("Conclusão: Cada Gota Conta", "A economia de combustível é um jogo de centavos que vira reais. Cada técnica que você aplica adiciona alguns por cento de economia. Se você conseguir reduzir 20% o consumo (de R$ 500 para R$ 400 por mês), são R$ 1.200 por ano de lucro extra. Use o MeuCorre para acompanhar seu gasto de gasolina por km e ver se suas técnicas estão funcionando. Em 30 dias, você vai saber exatamente quanto economizou.")
    ]),
    (5, "Melhores Horários e Zonas para Entregar em Cada App", "capa-5.png", "Descubra os melhores horários e regiões para maximizar seus ganhos no iFood, 99Food, Lalamove e Rappi.", [
        ("Como Funculta o Sistema de Corridas dos Apps", "Cada app de entrega tem um algoritmo que decide qual entregador recebe cada corrida. Esses algoritmos consideram: distância do entregador ao restaurante/loja, avaliação do entregador (5 estrelas = prioridade), tempo de resposta (aceitar rápido = mais corridas), taxa de aceitação (recusar muito = menos corridas), horário de pico (mais demanda = mais ofertas). Entender como o algoritmo funciona é o primeiro passo para receber melhores corridas. Quem entende o sistema ganha mais trabalhando menos."),
        ("Melhores Horários para iFood", "O iFood tem picos de demanda claros: Almoço (11h-14h): pico máximo, principalmente de segunda a sexta. Jantar (19h-22h): segundo pico, todos os dias. Fim de semana (sexta 19h a domingo 23h): alto volume, principalmente em regiões residenciais. Dias de chuva: demanda explode em todos os horários. Dias de jogo do Brasil: picos antes e depois das partidas. Melhores zonas: centros comerciais e residenciais de bairros de classe média-alta. Evite: zonas industriais (poucos restaurantes) e bairros muito periféricos (corridas longas e baixo valor)."),
        ("Melhores Horários para 99Food", "O 99Food tem demanda mais distribuída ao longo do dia, mas com picos: Almoço (11h30-13h30): pico moderado. Jantar (19h-21h): pico alto. Madrugada (23h-3h): pico em finais de semana, principalmente em áreas de balada. Vantagem do 99Food: menos entregadores competindo que o iFood, o que significa que você recebe corridas mais rápido. Melhores zonas: áreas universitárias, centros de bairros, zonas de comércio noturno."),
        ("Melhores Horários para Lalamove", "O Lalamove é diferente dos apps de comida — é entrega de mercadorias e documentos. Horários: Dias úteis (8h-18h): demanda constante, pico entre 10h-12h e 14h-17h. Sábado (9h-14h): demanda moderada. Domingo: praticamente parado. Vantagem: corridas de maior valor (R$ 20-80) e maior quilometragem. Desvantagem: precisa de baú ou mochila grande. Melhores zonas: centros comerciais, zonas industriais, áreas de escritórios."),
        ("Melhores Horários para Rappi", "A Rappi entrega de tudo: comida, supermercado, farmácia, eletrônicos. Horários: Almoço (11h-14h): pico de comida. Tarde (14h-18h): pico de farmácia e supermercado. Noite (19h-23h): pico de comida e conveniência. Madrugada (0h-5h): pico de farmácia 24h em finais de semana. Vantagem: variedade de produtos significa demanda em todos os horários. Melhores zonas: áreas residenciais de classe média, prédios comerciais, proximidades de shoppings."),
        ("Estratégia: Trabalhar com Vários Apps Simultaneamente", "A estratégia mais lucrativa é trabalhar com 2-3 apps ao mesmo tempo. Cada app tem seu pico em horário diferente, então você sempre tem demanda. Exemplo de rotina: 8h-11h: Lalamove (entregas de mercadorias). 11h-14h: iFood (almoço). 14h-18h: Rappi (farmácia/supermercado) ou Lalamove. 19h-22h: iFood + 99Food (jantar). 22h-0h: 99Food (madrugada, finais de semana). O MeuCorre permite lançar corridas de todos os apps e ver qual te paga mais por km. Com 30 dias de dados, você sabe exatamente quais apps priorizar em cada horário."),
        ("Como a Localização Afeta Seus Ganhos", "Ficar em uma boa 'zona quente' faz diferença. Apps priorizam entregadores próximos ao restaurante. Se você está a 500m, recebe a corrida. Se está a 3km, não recebe. Fique estacionado perto de aglomerados de restaurantes: shoppings, praças de alimentação, ruas comerciais. Evite ficar em zonas residenciais (longe dos restaurantes) — você vai receber corridas de entrega, não de coleta. Use o Google Maps para identificar clusters de restaurantes em sua cidade. E use o MeuCorre para registrar em quais zonas você ganha mais — depois de 2 semanas, você vai ver o padrão."),
        ("Conclusão: Dados São Seu Melhor Aliado", "Não existe sorte na entrega de apps — existe estratégia baseada em dados. Os melhores entregadores não são os que trabalham mais horas, mas os que trabalham nas horas certas, nas zonas certas, com os apps certos. Use o MeuCorre por 30 dias para coletar dados de suas corridas. Depois, analise: qual horário te deu mais lucro? Qual app pagou mais por km? Qual zona teve mais corridas curtas? Com essas respostas, otimize sua rotina e ganhe mais trabalhando menos.")
    ]),
    (6, "Equipamentos Essenciais para Entregadores de App", "capa-6.png", "Lista completa de equipamentos que todo entregador precisa ter para trabalhar com segurança e eficiência.", [
        ("Mochila Térmica: O Equipamento Mais Importante", "A mochila térmica é o equipamento #1 do entregador. Sem ela, você não pode trabalhar na maioria dos apps. Ela mantém a temperatura da comida (quente ou fria) durante o transporte. Tipos: 1) Térmica simples (R$ 50-80): mantém temperatura por 1-2h. Ideal para iniciantes. 2) Térmica premium (R$ 120-200): mantém por 3-4h, mais resistente, impermeável. Recomendada para quem trabalha 8h+. 3) Térmica profissional (R$ 250-400): isotermal com dupla parede, mantém por 6h+. Para quem faz entregas de longa distância. Como escolher: tamanho mínimo 25L (cabe 2-3 pedidos grandes), alças reforçadas (vai carregar muito peso), impermeável (chuva não pode entrar), fácil de limpar (vai derramar molho um dia). A MeuCorre tem ofertas de mochilas com desconto na aba 'Ofertas' do app."),
        ("Suporte de Celular para Moto", "O celular é sua ferramenta de trabalho — sem ele, sem corridas. O suporte precisa ser: resistente a vibração (moto vibra muito), universal (ajusta qualquer celular), com amortecedor (protege a câmera do celular), fácil de colocar e tirar (quando precisar usar o celular). Tipos: 1) Garra com mola (R$ 30-60): simples e funcional. 2) Magnético (R$ 50-100): prático mas pode derrubar o celular em buracos. 3) Com amortecedor (R$ 60-120): melhor opção, protege o celular. Invista em um bom suporte — um celular quebrado custa R$ 1.000-2.000 para trocar."),
        ("Capa de Chuva: Não Fique Parado Quando Chove", "Chuva é quando mais demanda existe — e quando muitos entregadores param por não ter capa. Uma boa capa de chuva: 1) Capa para o corpo (R$ 40-80): impermeável, com capuz, cobre até a cintura. 2) Capa para a moto (R$ 30-50): protebe o tanque e o assento. 3) Capa para a mochila (R$ 20-40): se a mochila não for impermeável. 4) Luvas impermeáveis (R$ 25-50): mãos secas = melhor controle. Com o conjunto completo, você continua entregando na chuva enquanto outros param — e ganha mais por causa da alta demanda."),
        ("Carregador Portátil (Power Bank)", "O celular gasta muita bateria com GPS, tela acesa, e apps rodando. Em um dia de 8h, a bateria não dura. Solução: power bank de 20.000 mAh (R$ 60-120). Dá para carregar o celular 3-4 vezes. Escolha um com saída USB-C de pelo menos 18W para carregamento rápido. Dica: leve o carregador de parede também — em paradas para almoço, carregue direto na tomada. Um celular sem bateria = sem corridas = sem dinheiro."),
        ("Fone de Ouvido Bluetooth", "O fone é importante para: ouvir as notificações de corrida (sem precisar olhar o celular), receber ligações de clientes (mãos livres), ouvir músicas/podcasts durante o trabalho. Escolha: fone bluetooth com gancho (não cai da orelha na vibração da moto), à prova d'água (suor e chuva), com bateria de 6h+ (R$ 50-150). Evite fones intra-auriculares que bloqueiam sons externos — você precisa ouvir o trânsito. Use apenas um lado para manter a atenção na rua."),
        ("Kit de Ferramentas Básicas", "Quebrou na rua? Com um kit básico, você resolve 80% dos problemas. Kit mínimo: 1) Chave de boca 10x12 e 14x17 (R$ 15). 2) Chave Allen (R$ 10). 3) Fita isolante (R$ 5). 4) Cabo de embreagem/acelerador reserva (R$ 15). 5) Fusíveis (R$ 5). 6) Lâmina de cortar corrente (R$ 10). 7) Bomba de ar portátil (R$ 25-50). Total: R$ 85-110. Guarde em uma bolsa sob o assento. Pode parecer desnecessário até você precisar — e vai precisar."),
        ("Roupa Adequada e EPIs", "1) Capacete (obrigatório por lei): com viseira (protege contra insetos e chuva). Invista em um bom capacete — sua cabeça vale mais que R$ 100. 2) Luvas: protegem as mãos no frio e em quedas. 3) Cotoveleiras e joelheiras: para quem roda muitos km, protegem em caso de queda. 4) Colete refletivo: obrigatório em algumas cidades, essencial para visibilidade noturna. 5) Bota ou tênis reforçado: protege os pés do calor do escapamento e em quedas. 6) Jaqueta ventada: protege do sol e vento sem esquentar. O MeuCorre tem ofertas de equipamentos na aba 'Ofertas'."),
        ("Conclusão: Invista em Seu Negócio", "Como entregador, você é uma empresa de um homem só. Seus equipamentos são seus ativos. Cada R$ 1 investido em equipamento de qualidade retorna em produtividade, segurança e durabilidade. Não economize no essencial (capacete, suporte de celular, mochila). Economize no acessório (fones caros, roupas de marca). Use o MeuCorre para registrar o custo de cada equipamento como despesa — isso reduz seu lucro tributável e te dá dinheiro de volta no imposto de renda. Comece pelo básico e vá melhorando conforme seu lucro aumenta.")
    ]),
    (7, "Gestão de Tempo para Entregadores: Como Rodar Mais em Menos Tempo", "capa-7.png", "Aprenda a otimizar rotas, gerenciar pausas e trabalhar nos horários de pico para maximizar seus ganhos.", [
        ("Por Que Gestão de Tempo é Crucial para Entregadores", "Como entregador, seu tempo é seu dinheiro. Cada minuto parado é um real não ganho. Mas isso não significa que você deve trabalhar 14 horas por dia. Significa que nas horas que você trabalha, precisa ser eficiente. Um entregador que trabalha 8 horas bem planejadas ganha mais que um que trabalha 12 horas sem planejamento. A diferença está na gestão de tempo: saber quando pausar, quando acelerar, qual rota fazer, qual corrida aceitar e qual recusar. Neste artigo, vou te mostrar como otimizar cada minuto do seu dia de trabalho."),
        ("Mapa do Seu Dia: Como Estruturar as Entregas", "Um dia eficiente de entregas tem estrutura. Não é sair e ficar esperando corrida. É planejar: 1) 7h-8h: preparação (revisar moto, abastecer, verificar app, posicionar-se em zona quente). 2) 8h-11h: entregas de mercadorias (Lalamove/Rappi — boa demanda matinal). 3) 11h-14h: pico de almoço (iFood/99Food — máxima demanda). 4) 14h-15h: pausa para almoço tarde e descanso. 5) 15h-18h: entregas mistas (Rappi farmácia/supermercado). 6) 18h-19h: pausa para jantar e reabastecer. 7) 19h-22h: pico de jantar (iFood/99Food). 8) 22h+: encerrar ou continuar se for fim de semana. Esse cronograma garante que você está sempre nas horas de pico e descansa nos vales."),
        ("Como Otimizar Rotas de Entrega", "A rota ideal é: coleta rápida + entrega rápida + retorno para zona quente. Para otimizar: 1) Aceite corridas com coleta próxima (menos de 1km de você). 2) Prefira entregas no mesmo bairro (menos km, menos tempo). 3) Use o Google Maps para ver o trânsito antes de aceitar. 4) Evite cruzar a cidade no horário de pico (1h no trânsito = 4-5 corridas perdidas). 5) Aprenda atalhos da sua região. 6) Decore os endereços dos restaurantes mais solicitados — você vai chegar e sair mais rápido. 7) Mantenha-se em zonas com aglomerado de restaurantes para sempre ter coletas próximas."),
        ("Quando Aceitar e Quando Recusar Corridas", "Nem toda corrida vale a pena. Aprenda a recusar as ruins para pegar as boas: ACEITE: corridas curtas (2-5km) com valor acima de R$ 10, coleta próxima (menos de 1km), entregas em zonas com muitos restaurantes (retorno rápido). RECUSE: corridas longas (10+km) com valor baixo (menos de R$ 20), coleta a mais de 3km de você, entregas em zonas remotas (retorno sem demanda), horários de pico com trânsito pesado para a direção da entrega. Mas cuidado: a taxa de aceitação importa para o algoritmo. Se recusar mais de 30% das corridas, o app reduz suas ofertas. A solução: em vez de recusar, deixe o tempo expirar (15 segundos) — não conta como recusada."),
        ("Gestão de Pausas: Quando Parar para Ganhar Mais", "Parar parece contraproducente, mas é essencial. Entregadores que não pausam: 1) Ficam exaustos após 6h e cometem erros (aceitam corridas ruins, erram rotas). 2) Têm mais risco de acidentes por cansaço. 3) Perdem eficiência — cada hora após a 8ª produz 30% menos. Pausas estratégicas: 1) 15 minutos entre o almoço e o jantar (14h-15h) para comer e descansar. 2) 10 minutos a cada 3 horas para alongar e hidratar. 3) 30 minutos para jantar (18h-18h30) antes do pico noturno. Total de pausas: 55 minutos em um dia de 10h. Parece muito? Na verdade, essas pausas aumentam sua produtividade nas horas de trabalho — você chega no pico de jantar descansado e ganha 20% mais."),
        ("Como Lidar com Tempos de Espera em Restaurantes", "O maior desperdício de tempo do entregador é esperar no restaurante. Enquanto espera, não ganha e não pode pegar outra corrida. Como minimizar: 1) Quando chegar, confirme imediatamente que é o entregador do pedido X. 2) Pergunte o tempo estimado de preparo. Se for mais de 10 minutos, avalie se vale a pena esperar. 3) Se o restaurante é conhecido por demorar, evite aceitar corridas dele. 4) Avise o cliente que está aguardando preparo (reduz reclamações). 5) Use o tempo de espera para: hidratar, ir ao banheiro, verificar próximas zonas quentes, lançar corridas no MeuCorre. 6) Se a espera for mais de 15 minutos, contate o suporte do app — às vezes eles cancelam e você recebe compensação."),
        ("Trabalhando em Dias de Chuva: Estratégia Especial", "Dias de chuva = demanda alta + menos entregadores = você ganha mais. Mas precisa se preparar: 1) Tenha capa de chuva sempre na moto. 2) Proteja o celular com capa impermeável. 3) Use luvas impermeáveis. 4) Reduza velocidade — pista molhada é escorregadia. 5) Aceite apenas corridas curtas (menos exposição à chuva). 6) Fique em zonas com cobertura (shoppings, galerias). 7) Aumente seu preço médio aceitando apenas corridas acima de R$ 15. 8) Faça pausas mais frequentes para secar e aquecer. Em dias de chuva, você pode ganhar 30-50% mais que em dias secos — se estiver preparado."),
        ("Conclusão: Tempo é o Único Recurso Que Não Se Recupera", "Você pode ganhar mais dinheiro, mas não pode recuperar tempo perdido. Cada hora bem gerida vale por duas mal geridas. As técnicas deste artigo não são teoria — são práticas usadas pelos entregadores que mais ganham no Brasil. Comece hoje: estruture seu dia, otimize rotas, faça pausas estratégicas, e use o MeuCorre para medir se suas mudanças estão funcionando. Em 30 dias, compare seu lucro por hora com o de antes. Você vai se surpreender com a diferença.")
    ]),
    (8, "Declaração de Imposto de Renda para Entregadores 2026", "capa-8.png", "Guia completo sobre IRPF, MEI e deduções para entregadores de aplicativo. Não pague imposto à toa.", [
        ("Entregadores Precisam Declarar Imposto de Renda?", "Sim, na maioria dos casos. Como entregador autônomo, você precisa declarar se: 1) Recebeu rendimentos tributáveis acima de R$ 33.919,80 no ano (2025). 2) Recebeu rendimentos isentos acima de R$ 40.000. 3) Teve ganho de capital ou operou na bolsa. 4) É MEI e faturou acima do limite. 5) Possui bens acima de R$ 300.000. Mesmo que não seja obrigado, é recomendável declarar — para receber restituição, comprovar renda (financiamento, aluguel) e evitar multa por obrigatoriedade não cumprida (R$ 165,74 a 20% do imposto devido)."),
        ("MEI vs Autônomo: Qual a Melhor Opção?", "MEI (Microempreendedor Individual): para faturamento até R$ 81.000/ano (R$ 6.750/mês). Pagamento fixo de R$ 70-80/mês (DAS). Tem CNPJ, nota fiscal, INSS, direito a auxílio-doença e aposentadoria. Não paga imposto de renda sobre o faturamento (paga só o DAS). Precisa declarar a DASN-SIMEI anualmente (simplificada). Autônomo sem MEI: sem CNPJ, sem INSS, sem direitos trabalhistas. Paga 15% de imposto sobre o lucro (carnê-leão). Precisa declarar IRPF completa. Recomendação: se você fatura até R$ 6.750/mês, faça MEI. É mais barato e dá mais direitos."),
        ("Como Declarar Como MEI", "Como MEI, você precisa de duas declarações: 1) DASN-SIMEI (Declaração Anual do MEI): informa o faturamento do ano. Prazo: até 31 de maio. Multa por atraso: R$ 50. 2) DIRPF (Declaração de Imposto de Renda Pessoa Física): se seus rendimentos (lucro do MEI + outros) ultrapassarem R$ 33.919,80. No lucro do MEI, você precisa separar: 28% se for comércio (entrega) = isento de IR. 72% = rendimento tributável. Exemplo: faturou R$ 60.000, lucro de R$ 40.000. 28% de R$ 40.000 = R$ 11.200 isento. R$ 28.800 tributável. O MeuCorre gera relatórios de faturamento e despesas que facilitam muito essa separação."),
        ("Deduções Que Entregadores Podem Fazer", "Deduções reduzem o imposto devido. Como entregador autônomo, você pode deduzir: 1) Gasolina: guarde notas fiscais ou use o MeuCorre para registrar. 2) Manutenção da moto: notas fiscais do mecânico. 3) Equipamentos: mochila, capacete, celular, suporte. 4) Plano de celular: parte proporcional ao uso profissional (ex: 80% se usa 80% para trabalho). 5) IPVA e seguro da moto: 100% dedutível se usado para trabalho. 6) Alimentação durante o trabalho: dedutível como despesa. 7) Depreciação da moto: calcule o valor da moto dividido por 5 anos. Total de deduções pode reduzir seu imposto em 30-50%. Sem registros, você não pode deduzir. Por isso o MeuCorre é tão importante — ele guarda tudo."),
        ("Como o MeuCorre Ajuda na Declaração", "O MeuCorre é a ferramenta ideal para a declaração de IR porque: 1) Registra TODAS as corridas com data, valor, app e km. 2) Registra TODAS as despesas por categoria (gasolina, manutenção, alimentação, equipamentos). 3) Calcula o lucro líquido automaticamente. 4) Permite exportar dados em JSON e CSV para o contador. 5) Mostra gráficos mensais que facilitam a conferência. 6) Funciona offline — você registra no dia, não precisa lembrar no fim do ano. 7) Backup em nuvem (PRO) garante que seus dados não se percam. No fim do ano, basta exportar o relatório e enviar para seu contador. Ele vai amarbar você por ter tudo organizado."),
        ("Erros Comuns na Declaração de Entregadores", "1) Não declarar por achar que ganha pouco: multa mínima R$ 165,74. 2) Declarar faturamento em vez de lucro: você paga imposto sobre o lucro, não sobre o faturamento. 3) Não separar isento de tributável (MEI): 28% do lucro é isento, 72% é tributável. 4) Não ter comprovantes de despesa: sem nota fiscal ou registro, não pode deduzir. 5) Esquecer de declarar rendimentos de múltiplos apps: cada app é uma fonte pagadora. 6) Não declarar rendimento de cashback: programas como Shell Box geram rendimento tributável. 7) Confundir despesa pessoal com profissional: gasolina da moto é profissional, gasolina do carro da família é pessoal. Use o MeuCorre para separar tudo."),
        ("Passo a Passo para Declarar em 2026", "1) Reúna todos os documentos: informes de rendimentos dos apps, notas fiscais de despesas, relatório do MeuCorre. 2) Separe faturamento de lucro (use o MeuCorre para ver o lucro líquido). 3) Se for MEI, preencha a DASN-SIMEI primeiro. 4) Abra o programa da Receita Federal (IRPF 2026). 5) Preencha os rendimentos: 28% do lucro como isento, 72% como tributável. 6) Lance as deduções: despesas com a moto, equipamentos, celular. 7) Inclua os bens: moto, celular. 8) Verifique se há imposto a pagar ou restituir. 9) Envie a declaração até 31 de maio de 2026. 10) Guarde todos os comprovantes por 5 anos."),
        ("Conclusão: Organização é o Melhor Remédio", "Declarar imposto de renda como entregador não precisa ser um pesadelo. Com organização e as ferramentas certas, é simples. O segredo é registrar tudo ao longo do ano, não tentar lembrar em abril. Use o MeuCorre diariamente, exporte o relatório no fim do ano, e leve para o contador. Ele faz o resto. E lembre-se: cada despesa registrada é um imposto menor pago. Cada corrida não registrada é uma dedução perdida. Comece hoje a se organizar para a declaração de 2026.")
    ]),
    (9, "Qual App de Entrega Dá Mais Dinheiro? Comparativo 2026", "capa-9.png", "Comparativo completo entre iFood, 99Food, Lalamove e Rappi. Descubra qual paga mais por km.", [
        ("Metodologia do Comparativo", "Este comparativo foi baseado em dados reais de entregadores brasileiros durante 2025-2026. Analisamos: valor médio por corrida, km médio por corrida, ganho por km, número de corridas por hora, ganho por hora, e lucro líquido por hora (descontando gasolina e despesas). Os dados foram coletados através do app MeuCorre, que registra automaticamente todas essas métricas. Importante: os valores variam por cidade, região e horário. Use estes dados como referência, não como regra absoluta. O ideal é que você teste cada app por 2 semanas e compare com seus próprios dados no MeuCorre."),
        ("iFood: O Gigante do Mercado", "iFood é o maior app de entrega de comida do Brasil. Volume de corridas: altíssimo (principalmente no almoço e jantar). Valor médio por corrida: R$ 12-18. Km médio: 3-6 km. Ganho por km: R$ 2,50-3,50. Corridas por hora (pico): 4-6. Corridas por hora (vale): 1-2. Ganho por hora (pico): R$ 50-80. Ganho por hora (média): R$ 30-45. Vantagens: muito volume, fácil achar corridas, app estável. Desvantagens: muita concorrência (muitos entregadores), avaliações pesam muito, comissões altas reduzem o valor das corridas. Melhor para: quem quer volume e trabalha nas horas de pico."),
        ("99Food: A Alternativa em Crescimento", "99Food é o app de entrega da 99 (mesma empresa da 99Táxi). Volume: médio (menos que iFood, mas crescendo). Valor médio por corrida: R$ 10-16. Km médio: 3-5 km. Ganho por km: R$ 2,80-3,80. Corridas por hora (pico): 3-5. Ganho por hora (pico): R$ 40-70. Ganho por hora (média): R$ 25-40. Vantagens: menos concorrência que iFood, promoções frequentes para entregadores, integração com 99Táxi (pode fazer os dois). Desvantagens: menos volume total, algumas regiões têm pouca cobertura. Melhor para: complementar o iFood nos vales de demanda."),
        ("Lalamove: Entregas de Maior Valor", "Lalamove é entrega de mercadorias e documentos (não comida). Volume: baixo-médio, mas corridas de valor alto. Valor médio por corrida: R$ 25-60. Km médio: 8-15 km. Ganho por km: R$ 2,00-4,00. Corridas por hora: 1-3. Ganho por hora (pico): R$ 40-80. Ganho por hora (média): R$ 30-50. Vantagens: corridas de alto valor, menos corridas para mesmo ganho, menos desgaste de parar e partir. Desvantagens: precisa de mochila/baú grande, maior km rodado (mais gasolina), horário comercial (pouca demanda à noite). Melhor para: manhãs e tardes (8h-18h) em dias úteis."),
        ("Rappi: Variedade de Entregas", "Rappi entrega de tudo: comida, supermercado, farmácia, eletrônicos. Volume: médio-alto. Valor médio por corrida: R$ 12-22. Km médio: 3-7 km. Ganho por km: R$ 2,20-3,50. Corridas por hora (pico): 3-5. Ganho por hora (pico): R$ 40-70. Ganho por hora (média): R$ 25-40. Vantagens: demanda durante todo o dia (não só almoço/jantar), variedade de tipos de entrega. Desvantagens: às vezes exige compras no supermercado (demora), app pode ser instável. Melhor para: tardes (14h-18h) quando iFood e 99Food estão em vale."),
        ("Tabela Comparativa de Ganho por Km", "Baseado em dados reais de entregadores em São Paulo e Rio de Janeiro (2025-2026): iFood: R$ 3,00/km média. 99Food: R$ 3,20/km média. Lalamove: R$ 3,50/km média. Rappi: R$ 2,80/km média. Mas o ganho por km não conta tudo — o número de corridas por hora também importa. iFood tem 5 corridas/hora no pico vs Lalamove com 2. No final, o ganho por hora é similar, mas o desgaste é diferente: iFood = mais paradas e partidas (desgaste de moto), Lalamove = mais km (mais gasolina). Use o MeuCorre para calcular seu próprio ganho por km em cada app e descobrir qual é o melhor para você."),
        ("Estratégia: Qual App Usar e Quando", "A melhor estratégia é combinar apps: Manhã (8h-11h): Lalamove (mercadorias, alto valor). Almoço (11h-14h): iFood (máximo volume). Tarde (14h-18h): Rappi (farmácia/supermercado) ou 99Food. Jantar (19h-22h): iFood + 99Food (dupla fonte). Madrugada finais de semana: 99Food (pouca concorrência). Essa combinação garante que você sempre tem demanda e diversifica a renda. Se um app sair do ar ou reduzir corridas, você tem os outros. Use o MeuCorre para registrar qual app te dá mais lucro por hora e ajuste sua estratégia mensalmente."),
        ("Conclusão: Não Existe Melhor App, Existe Melhor Estratégia", "O 'melhor app' depende da sua cidade, seu horário, sua zona e sua moto. O que funciona em São Paulo pode não funcionar em Belo Horizonte. O que rende no almoço pode não render à noite. A única forma de saber qual é o melhor para VOCÊ é testar e medir. Baixe o MeuCorre (gratuito), trabalhe com 2-3 apps por 30 dias, e compare: qual te deu mais lucro por km? Qual por hora? Qual em qual horário? Com esses dados, você otimiza sua rotina e ganha mais. Os melhores entregadores não são os que trabalham mais — são os que trabalham com inteligência.")
    ]),
    (10, "Como Se Tornar um Entregador 5 Estrelas em Todos os Apps", "capa-10.png", "Dicas práticas para conseguir avaliações máximas, fidelizar clientes e ganhar prioridade nos apps de entrega.", [
        ("Por Que Avaliações 5 Estrelas Importam", "As avaliações (estrelas) são a métrica mais importante para um entregador nos apps. Elas determinam: 1) Prioridade no algoritmo — entregadores 5 estrelas recebem corridas melhores primeiro. 2) Acesso a promoções e bônus — muitos apps reservam as melhores corridas para quem tem avaliação alta. 3) Continuidade no app — abaixo de 4 estrelas, o app pode te desativar. 4) Bônus de qualidade — alguns apps pagam extra para entregadores com avaliação acima de 4.8. Uma avaliação 5 estrelas não é um 'presente' do cliente — é o resultado de um trabalho bem feito. E dá para controlar isso."),
        ("Os 10 Mandamentos do Entregador 5 Estrelas", "1) Entregue rápido. O cliente está com fome e esperando. Quanto mais rápido, mais estrela. 2) Não derrame. Acomode a comida com cuidado, use suporte na moto, evite buracos. 3) Seja educado. 'Bom dia, sou o Carlos do iFood, estou a caminho.' Uma mensagem muda tudo. 4) Não se perca. Use o GPS, mas confirme o endereço antes de sair. 5) Avise se vai atrasar. O cliente prefere saber do atraso do que ficar esperando sem explicação. 6) Entregue com sorriso. Mesmo cansado, um 'bom apetite' vale uma estrela. 7) Verifique o pedido. Se faltar item, avise o restaurante e o cliente. 8) Cuide da aparência. Roupa limpa, sem cheiro de cigarro. 9) Não use o celular enquanto dirige. Segurança em primeiro lugar. 10) Peça avaliação. 'Se gostou do serviço, pode avaliar com 5 estrelas? Ajuda muito!' Funciona."),
        ("Como Lidar com Clientes Difíceis", "Nem todo cliente é fácil. Alguns reclamam de tudo, outros não respondem, alguns dão endereço errado. Como lidar: 1) Cliente que reclama da comida: não é sua culpa. Diga 'sinto muito, entre em contato com o restaurante ou o app'. 2) Cliente que não atende: ligue 3 vezes (regra do app), aguarde 5 minutos, se não atender, contate o suporte. 3) Endereço errado: confirme por mensagem antes de sair. Se chegou e não é o lugar certo, ligue para confirmar. 4) Cliente irritado por atraso causado pelo restaurante: explique que aguardou preparo, não foi sua culpa. 5) Cliente que pede para subir no andar: o app recomenda entregar na portaria, mas se for seguro e rápido, suba. 6) Nunca discuta com o cliente. Mesmo com razão, você perde na avaliação. Respire, seja profissional, siga em frente."),
        ("Como Recuperar Sua Avaliação Se Caiu", "Se sua avaliação caiu para 4.5 ou menos: 1) Identifique o problema. Foi atraso? Comida derramada? Falta de educação? 2) Corrija o problema imediatamente. 3) Faça 20 corridas perfeitas seguidas. Cada 5 estrelas sobe a média. 4) Peça avaliação para cada cliente satisfeito. 5) Evite corridas de alto risco (longas, em trânsito pesado, em bairros difíceis) até recuperar. 6) Trabalhe em horários de baixa demanda (menos pressão, menos risco de erro). 7) Se um cliente te deu 1 estrela injustamente, contate o suporte do app. Eles podem remover avaliações abusivas. Em 1-2 semanas de trabalho focado, você volta para 4.8+."),
        ("Comunicação: A Chave para 5 Estrelas", "A comunicação com o cliente é o que separa 4 estrelas de 5. Envie mensagens em 3 momentos: 1) Ao aceitar a corrida: 'Olá! Sou o [nome] do [app], já estou a caminho do restaurante.' 2) Ao coletar: 'Já peguei seu pedido! Estou a caminho, chego em aproximadamente [X] minutos.' 3) Ao entregar: 'Cheguei! Bom apetite! Se gostou do serviço, sua avaliação 5 estrelas ajuda muito. Obrigado!' Essas 3 mensagens levam 30 segundos para enviar e podem elevar sua avaliação de 4.2 para 4.8 em 2 semanas. Os apps permitem enviar mensagens pré-formatadas — crie as suas e use sempre."),
        ("Dicas de Apresentação Pessoal", "A aparência do entregador influencia a avaliação. Não precisa de roupa de marca, mas: 1) Roupa limpa e sem rasgos. 2) Capacete limpo (viseira sem arranhões). 3) Mochila limpa por fora (cliente vê). 4) Sem cheiro de cigarro ou suor excessivo. 5) Unhas limpas (cliente vê quando você entrega a sacola). 6) Máscara se estiver doente (protege o cliente). 7) Sorria ao entregar (mesmo de máscara, os olhos sorriem). 8) Tenha caneta própria (para assinatura de comprovante). 9) Tenha troco se o pagamento for em dinheiro. 10) Agradeça sempre: 'Obrigado, bom apetite!'"),
        ("Como Fidelizar Clientes e Restaurantes", "Clientes e restaurantes que gostam de você podem te dar prioridade e melhores avaliações. Com restaurantes: 1) Chegue pontualmente para a coleta. 2) Seja educado com a equipe. 3) Não reclame do tempo de preparo (não é com você). 4) Ajude se precisarem de algo rápido (segurar a porta, etc). 5) Diga 'obrigado' ao sair. Com clientes: 1) Entregue sempre rápido e com educação. 2) Se for um cliente recorrente (mesmo endereço), comente 'que bom ver você de novo'. 3) Se a entrega for para um prédio, cumprimente o porteiro. 4) Em dias de chuva, peça desculpa pelo possível atraso. Fidelização gera avaliações 5 estrelas espontâneas, sem precisar pedir."),
        ("Conclusão: 5 Estrelas é Hábito, Não Sorte", "Ninguém ganha 5 estrelas por sorte. É o resultado de hábitos consistentes: rapidez, educação, cuidado com a comida, comunicação clara, e apresentação adequada. Comece hoje a aplicar os 10 mandamentos. Em 30 dias, sua avaliação vai subir. Em 60 dias, você estará recebendo melhores corridas. Em 90 dias, será um dos entregadores prioritários do app. E lembre-se: use o MeuCorre para registrar suas corridas e ver quais horários e regiões te dão as melhores avaliações. Dados + hábitos = 5 estrelas garantidas.")
    ])
]

# Add remaining posts to the list
for num, title, cover, desc, sections in remaining_topics:
    POSTS.append({
        "num": num,
        "title": title,
        "cover": cover,
        "desc": desc,
        "h2_sections": sections,
    })

def generate_html(post):
    num = post["num"]
    title = post["title"]
    desc = post.get("desc", "")
    cover = post["cover"]
    sections = post["h2_sections"]

    html = f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"/>
<meta name="description" content="{desc}"/>
<title>{title}</title>
</head>
<body>
<div style="max-width:800px;margin:0 auto;font-family:Georgia,serif;line-height:1.8;color:#333;">

<!-- Capa -->
<div style="margin-bottom:30px;">
<img src="capa-{num}.png" alt="{title}" style="width:100%;border-radius:12px;"/>
</div>

<h1 style="font-size:28px;color:#064E3B;margin-bottom:10px;">{title}</h1>
<p style="font-size:14px;color:#666;font-style:italic;margin-bottom:30px;">{desc}</p>

"""
    for h2_title, content in sections:
        html += f"""<h2 style="font-size:22px;color:#10B981;margin-top:40px;margin-bottom:15px;">{h2_title}</h2>
<p style="font-size:16px;margin-bottom:20px;">{content}</p>
"""

    html += """<hr style="margin:40px 0;border:none;border-top:1px solid #ddd;"/>
<p style="font-size:14px;color:#666;text-align:center;">
<a href="https://meucorre.vercel.app" style="color:#10B981;">Baixe o MeuCorre grátis</a> — o app que ajuda entregadores a controlarem corridas, despesas e lucro real.
</p>
</div>
</body>
</html>"""

    return html

# Generate all posts
for post in POSTS:
    html = generate_html(post)
    filename = f"post-{post['num']:02d}.html"
    filepath = os.path.join(OUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
    word_count = len(html.split())
    print(f"  ✓ {filename} — {word_count} palavras")

print(f"\n=== {len(POSTS)} postagens geradas em {OUT_DIR} ===")
print(f"Capas em: /home/z/my-project/download/blog-covers/")
